# Generated by Django 5.0.4 on 2024-04-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.TextField(blank=True, null=True)),
                ('finish_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
